### ISSUE TITLE
Congratulations

### ISSUE THREAD

**Issue by llrs** [emunte/vaRHC#2]
Congrats on your publication and work!

I saw that the package is meant to go to CRAN. 
However, I found that it has more than 20 dependencies (without counting the suggested packages). This is a hard limit for CRAN. You will need to reduce the dependencies to make sure that CRAN accepts the package. 

Good luck!

**Comment by emunte** [comment]
Dear Lluis,

First of all thanks for your interest!
You are totally right, we are now working on some improvements and one is about reducing the number of dependencies, indeed.
Thank you so much for your feedback.

Best wishes
